### ISSUE TITLE
Not updating the thread

### ISSUE THREAD

**Issue by RocketFoot** [RevertIT/mybb-rt_chatgpt#11]
Everything seems to be working however, the thread in the forum is not updated with the ChatGPT output.  The thread that is created when a question is asked is posted immediately and reads: 

`Generating response... It will take up to five minutes for this message to be updated.

If this message is not updated within five minutes, please report it to the administrator.`

I have forced the task manager to run as well as waited 24 hours but the thread has still not updated even though I see the correct answer in the logs.  Also, the answer repeats once after 5 minutes so there are 2 log entries.

**Comment by RevertIT** [comment]
Hi,

Sorry for late response, you can test out the latest pre-release (make sure to uninstall and install again the plugin) - https://github.com/RevertIT/mybb-rt_chatgpt/releases/tag/v1.2

**Comment by RevertIT** [comment]
That really makes no sense to behave like that. Either it wouldn't work for any topic or it would work for all. 

Without providing the logs from the chatgpt logs section inside your ACP, I can't help you debug the issue.

https://github.com/RevertIT/mybb-rt_chatgpt/releases/tag/v1.1b

**Comment by RocketFoot** [comment]
Here is a screen shot...it is also repeating the answer in logs over and over!

![ScreenHunter_1332 Jul  29 05 45](https://github.com/RevertIT/mybb-rt_chatgpt/assets/139809810/63e62d73-b24e-4ec6-925f-7dbaf6456335)

**Comment by RocketFoot** [comment]
I just tested 1.1b and still no post update...here is the log entry:

`<html><body>


  | Message:   [url=LINK_HERE][img]IMAGE_URL_HERE[/img][/url] | cmpl-7hbebReEutAvITlg6j8eHYM3BQDtQ | text-davinci-003 | 101 | OpenAI Assistant - Reply to thread |   | Less than 1 minute ago
-- | -- | -- | -- | -- | -- | -- | --



</body>
</html>`

**Comment by RevertIT** [comment]
The logs are showing that it worked correctly, make sure the bot has permissions to update the thread.

And when you force run the task, it still doesn't update?

**Comment by RocketFoot** [comment]
Bot is a supermod with access to post and edit in the forum.  It actually DOES update when I force run the task.  If I post a question and wait for the posted 5 minutes or more, it never edits/updates the post and the log keeps showing repeated entries of the same answer.
