### ISSUE TITLE
Issue 1.2b

### ISSUE THREAD

**Issue by ZorryTheKid** [RevertIT/mybb-rt_chatgpt#14]
Hi, i've this on my log 

| Invalid type for 'messages': expected an array of objects, but got an object instead. 
| Unable to receive data from getResponse() method.

PS nothing change if i use 3.5 or 4 

Tnx

**Comment by RevertIT** [comment]
Posted new update here on github, try downloading code and replacing current GPT, it should work.

**Comment by ZorryTheKid** [comment]
Works! It's truly a pleasure to have had a quick and decisive response with a new release! Thank you

**Comment by RevertIT** [comment]
Can you download the code again and test it? Now replies are not visible to public (only to moderators) until chatpgt response kicks in.

**Comment by ZorryTheKid** [comment]
sorry for delay. Now my boot works ok, prompt is fine, and approve users presentation in a logical manner ena coerent. Now, i will try new version, soon some feedback

**Comment by RevertIT** [comment]
It should work the same, the only difference is that the newly made post is set `visible` = 0 on creation, and it should appear once the task is run.

Are there any error logs, and do you see the posts in moderation panel waiting approval?

**Comment by ZorryTheKid** [comment]
Yes, all works fine 👍 tnx
